filter:
    paths: [src/*]
tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    external_code_coverage: true
build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=some-file'
                coverage:
                    file: 'some-file'
                    format: 'php-clover'